### ISSUE TITLE
Deleting a highlighted configuration channel removes the channel directly above it.

### ISSUE THREAD

**Issue by leesecho** [LabVIEW-DCAF/Scan-Engine-Module#29] opened 2017-02-16 16:24 UTC
When attempting to remove a highlighted channel from the "Scan Engine Settings" table, I deleted the channel in the row above. As there is no "undo" feature, a workaround isn't possible.

**Comment by pollockm** [comment] 2017-02-16 16:25
Replaces https://github.com/LabVIEW-DCAF/TagEditorCore/issues/283

**Comment by Beazurt** [comment] 2017-02-16 16:30
This is a duplicate of issue #28

**Closed by Beazurt** 2017-02-16 16:30 UTC
Labels: bug

**Comment by pollockm** [comment] 2017-02-16 19:39
:shipit:
